# Generated by Django 5.2.12 on 2026-03-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='brand',
        ),
    ]
