# Generated by Django 5.2.12 on 2026-03-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trk', '0002_rename_model_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelentry',
            name='odometer',
            field=models.FloatField(),
        ),
    ]
