# Generated by Django 5.2.12 on 2026-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trk', '0003_alter_fuelentry_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='odometer',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
