# Generated by Django 5.2.12 on 2026-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trk', '0004_servicerecord_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='full_tank',
            field=models.BooleanField(default=False),
        ),
    ]
